# Ruby cops
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Send:
  Enabled: true

# Additional Configurations
Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 130

Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/SymbolArray:
  EnforcedStyle: brackets
